# syntax=docker/dockerfile:1

# Adapted from Dockerfile generated by 'docker init' (for python);
# changed to make it multi-staged (build and final)

# Use the python base image so we can pip install without a hassle
# (Debian apt-installed python wants packages either from apt or in a venv)
FROM python:latest AS build

# Build UShER from source
RUN apt-get update && apt-get install -y sudo
WORKDIR /usher
RUN git clone https://github.com/yatisht/usher.git
RUN cd usher \
    && bash -x install/installUbuntu.sh

WORKDIR /app

COPY pyproject.toml .
COPY viral_usher viral_usher

# Nextclade is a Rust app so all we need to do is grab its binary.
# nextclade_to_maple is my noob Rust app so for some reason it's necessary to unzip a .zip.
RUN mkdir bin && cd bin \
    && wget -O nextclade https://github.com/nextstrain/nextclade/releases/latest/download/nextclade-x86_64-unknown-linux-gnu \
    && wget -O nextclade_to_maple.zip https://github.com/AngieHinrichs/nextclade_to_maple/releases/latest/download/nextclade_to_maple-x86_64-unknown-linux-gnu.zip \
    && unzip nextclade_to_maple.zip \
    && rm nextclade_to_maple.zip \
    && chmod a+x *


# Done with build stage; set up final image

FROM python:latest

WORKDIR /app

# Prevents Python from writing pyc files.
ENV PYTHONDONTWRITEBYTECODE=1

# Keeps Python from buffering stdout and stderr to avoid situations where
# the application crashes without emitting any logs due to buffering.
ENV PYTHONUNBUFFERED=1

# Install usher lib dependencies that are available from apt-get
RUN apt-get update && apt-get install -y --no-install-recommends \
    libboost-filesystem-dev libboost-program-options-dev libboost-iostreams-dev \
    libprotoc-dev openmpi-bin libopenmpi-dev

# Create a non-privileged user that the app will run under by default.
# See https://docs.docker.com/go/dockerfile-user-best-practices/
RUN apt-get update && apt-get install -y adduser
ARG UID=10001
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    appuser

# Done with all the apt-get stuff, clean up to save space.
RUN apt-get autoclean && rm -rf /var/lib/apt/lists/*

# Install usher_to_taxonium
RUN python3 -m pip install taxoniumtools

# Copy the python source code and Rust app bin into the container.
WORKDIR /app
COPY --from=build /app ./
# Install python dependencies and script.
RUN python3 -m pip install .

# Copy the built-from-source libs and usher executables into the container's /app/lib
RUN mkdir /app/lib
COPY --from=build \
    /usher/usher/build/tbb_cmake_build/tbb_cmake_build_subdir_release/libtbbmalloc_proxy.so.2 \
    /usher/usher/build/tbb_cmake_build/tbb_cmake_build_subdir_release/libtbbmalloc.so.2 \
    /usher/usher/build/tbb_cmake_build/tbb_cmake_build_subdir_release/libtbb_preview.so.2 \
    /usher/usher/build/isa-l-2.30.0/.libs/libisal.so.2 \
    /app/lib/
COPY --from=build /usher/usher/build/usher /usher/usher/build/usher-sampled \
    /usher/usher/build/matUtils /usher/usher/build/matOptimize \
    /usher/usher/build/faToVcf \
    /app/bin

# Switch to the non-privileged user to run the application.  After this we don't have privileges to change any files.
USER appuser

WORKDIR /data

ENV PATH=/app/bin:$PATH
# Tell executables about /app/lib
ENV LD_LIBRARY_PATH=/app/lib

# Run the application with config passed in via environment.
# TODO
#CMD ["viral_usher_build", "--config", "${VIRAL_USHER_CONFIG}"]
CMD ["bash"]
